@startuml

interface Habilidades<T> {
  {abstract}
  +usarHabilidad(T habilidad)
}

abstract class Personaje {
  -nombrePersonaje: String
  -nivel: int
  {abstract}
  +Personaje(nombrePersonaje: String, nivel: int)
  {abstract}
  +atacar(): void
  +usarHabilidad(habilidad: String): void
}

class PersonajeFisico {
  +PersonajeFisico(nombrePersonaje: String, nivel: int)
  +atacar(): void
  +usarHabilidadFisica(): void
}

class PersonajeMagico {
  +PersonajeMagico(nombrePersonaje: String, nivel: int)
  +atacar(): void
  +lanzarHechizo(): void
}

Personaje --|> Habilidades
PersonajeFisico --|> Personaje
PersonajeMagico --|> Personaje

@enduml
